# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: motor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmotor.proto\"\xa9\x01\n\x0cMotorRequest\x12\x17\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x07.Action\x12\x12\n\x05power\x18\x02 \x01(\x02H\x00\x88\x01\x01\x12\x10\n\x03rpm\x18\x03 \x01(\x02H\x01\x88\x01\x01\x12\x18\n\x0brevolutions\x18\x04 \x01(\x02H\x02\x88\x01\x01\x12\x13\n\x06offset\x18\x05 \x01(\x02H\x03\x88\x01\x01\x42\x08\n\x06_powerB\x06\n\x04_rpmB\x0e\n\x0c_revolutionsB\t\n\x07_offset\"d\n\rMotorResponse\x12\x17\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x07.Action\x12\x12\n\x05val_b\x18\x02 \x01(\x08H\x00\x88\x01\x01\x12\x12\n\x05val_f\x18\x03 \x01(\x02H\x01\x88\x01\x01\x42\x08\n\x06_val_bB\x08\n\x06_val_f*\x88\x01\n\x06\x41\x63tion\x12\x0c\n\x08NoAction\x10\x00\x12\x0c\n\x08SetPower\x10\x01\x12\t\n\x05GoFor\x10\x02\x12\x08\n\x04GoTo\x10\x03\x12\x15\n\x11resetZeroPosition\x10\x04\x12\x0f\n\x0bgetPosition\x10\x05\x12\x08\n\x04Stop\x10\x06\x12\r\n\tIsPowered\x10\x07\x12\x0c\n\x08IsMoving\x10\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'motor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTION._serialized_start=290
  _ACTION._serialized_end=426
  _MOTORREQUEST._serialized_start=16
  _MOTORREQUEST._serialized_end=185
  _MOTORRESPONSE._serialized_start=187
  _MOTORRESPONSE._serialized_end=287
# @@protoc_insertion_point(module_scope)
