# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csensor.proto\",\n\rSensorRequest\x12\x1b\n\x06sensor\x18\x01 \x01(\x0e\x32\x0b.SensorType\"\x1f\n\x0eSensorResponse\x12\r\n\x05value\x18\x01 \x01(\x02*E\n\nSensorType\x12\x0c\n\x08NoSensor\x10\x00\x12\x0f\n\x0bTemperature\x10\x01\x12\x0b\n\x07\x42\x61ttery\x10\x02\x12\x0b\n\x07\x43ounter\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SENSORTYPE._serialized_start=95
  _SENSORTYPE._serialized_end=164
  _SENSORREQUEST._serialized_start=16
  _SENSORREQUEST._serialized_end=60
  _SENSORRESPONSE._serialized_start=62
  _SENSORRESPONSE._serialized_end=93
# @@protoc_insertion_point(module_scope)
