# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wrapper.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import motor_pb2 as motor__pb2
import sensor_pb2 as sensor__pb2
import error_pb2 as error__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rwrapper.proto\x1a\x0bmotor.proto\x1a\x0csensor.proto\x1a\x0b\x65rror.proto\"g\n\x0eWrappedRequest\x12\'\n\rsensorRequest\x18\x01 \x01(\x0b\x32\x0e.SensorRequestH\x00\x12%\n\x0cmotorRequest\x18\x02 \x01(\x0b\x32\r.MotorRequestH\x00\x42\x05\n\x03msg\"\xa5\x01\n\x0fWrappedResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12)\n\x0esensorResponse\x18\x02 \x01(\x0b\x32\x0f.SensorResponseH\x00\x12\'\n\rmotorResponse\x18\x03 \x01(\x0b\x32\x0e.MotorResponseH\x00\x12\'\n\rerrorResponse\x18\x04 \x01(\x0b\x32\x0e.ErrorResponseH\x00\x42\x05\n\x03msgb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wrapper_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WRAPPEDREQUEST._serialized_start=57
  _WRAPPEDREQUEST._serialized_end=160
  _WRAPPEDRESPONSE._serialized_start=163
  _WRAPPEDRESPONSE._serialized_end=328
# @@protoc_insertion_point(module_scope)
